//--------------------------------------------------------------------------------
// sudo apt install libmariadb-dev libmariadb-dev-compat
//--------------------------------------------------------------------------------
const std = @import("std");
const c = @import("mysql-dynamic.zig");
//--------------------------------------------------------------------------------
pub fn main() !void {
    //------------------------------------------------------------
    const HOST = "127.0.0.1";
    const PORT = 3306;
    const USER = "root";
    const PASSWD = "";
    const DB = null;
    const CLIENT_FLAG = c.CLIENT_MULTI_STATEMENTS;
    //------------------------------------------------------------
    try c.init();
    defer c.deinit();
    //------------------------------------------------------------
    const db_handle = c.mysql_init(null);
    if (db_handle == null) {
        return error.MySQLInitFailed;
    }
    defer _ = c.mysql_close(db_handle);
    //------------------------------------------------------------
    if (c.mysql_real_connect(
        db_handle,
        HOST,
        USER,
        PASSWD,
        DB,
        PORT,
        null,
        CLIENT_FLAG,
    ) == null) {
        std.debug.print(
            "mysql_real_connect: {s}\n",
            .{c.mysql_error(db_handle)},
        );
        return error.MySQLConnectionFailed;
    }
    //------------------------------------------------------------
    std.debug.print("connected to {s}:{d}\n", .{ HOST, PORT });
    //------------------------------------------------------------
    {
        if (c.mysql_query(db_handle, "SELECT VERSION();") != 0) {
            std.debug.print(
                "mysql_query: {s}\n",
                .{c.mysql_error(db_handle)},
            );
            return error.MySQLQueryError;
        }

        const result = c.mysql_store_result(db_handle);
        if (result == null) {
            return error.MySQLResultError;
        }
        defer c.mysql_free_result(result);

        while (c.mysql_fetch_row(result)) |row| {
            if (row[0]) |version| {
                std.debug.print("version: {s}\n", .{version});
            }
        }
    }
    //------------------------------------------------------------
    {
        const sql =
            \\CREATE DATABASE IF NOT EXISTS test;
            \\USE test;
            \\DROP TABLE IF EXISTS cars;
            \\CREATE TABLE cars(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), price INT DEFAULT 0 NOT NULL, PRIMARY KEY(id));
            \\INSERT INTO cars(name, price) VALUES('Skoda', 9000);
            \\INSERT INTO cars(name, price) VALUES('Audi', 52642);
        ;

        if (c.mysql_query(db_handle, sql) != 0) {
            std.debug.print("mysql_query: {s}\n", .{c.mysql_error(db_handle)});
            return error.MySQLQueryError;
        }

        // consume every result generated by each line
        while (true) {
            const result = c.mysql_store_result(db_handle);

            if (result != null) {
                c.mysql_free_result(result);
            } else if (c.mysql_field_count(db_handle) != 0) {
                std.debug.print("mysql_store_result: {s}\n", .{c.mysql_error(db_handle)});
                return error.MySQLResultError;
            }

            const rc = c.mysql_next_result(db_handle);

            if (rc == 0) continue;

            if (rc > 0) {
                std.debug.print("mysql_next_result: {s}\n", .{c.mysql_error(db_handle)});
                return error.MySQLQueryError;
            }

            break;
        }
    }
    //------------------------------------------------------------
    {
        if (c.mysql_query(db_handle, "SELECT * FROM cars;") != 0) {
            std.debug.print(
                "mysql_query: {s}\n",
                .{c.mysql_error(db_handle)},
            );
            return error.MySQLQueryError;
        }

        const result = c.mysql_store_result(db_handle);
        if (result == null) {
            return error.MySQLResultError;
        }
        defer c.mysql_free_result(result);

        while (c.mysql_fetch_row(result)) |row| {
            std.debug.print(
                "id: {s}, name: {s}, price: {s}\n",
                .{ row[0].?, row[1].?, row[2].? },
            );
        }
    }
    //------------------------------------------------------------
}
//--------------------------------------------------------------------------------
