//--------------------------------------------------------------------------------
// sudo apt install libmariadb-dev libmariadb-dev-compat
// zig translate-c -lc /usr/include/mysql/mysql.h > mysql.zig
//--------------------------------------------------------------------------------
const std = @import("std");
//--------------------------------------------------------------------------------
pub fn main() !void {
    //------------------------------------------------------------
    const HOST = "127.0.0.1";
    const PORT = 3306;
    const USER = "root";
    const PASSWD = "";
    const DB = null;
    const CLIENT_FLAG = CLIENT_MULTI_STATEMENTS;
    //------------------------------------------------------------
    const db_handle = mysql_init(null);
    if (db_handle == null) {
        return error.MySQLInitFailed;
    }
    defer _ = mysql_close(db_handle);
    //------------------------------------------------------------
    if (mysql_real_connect(
        db_handle,
        HOST,
        USER,
        PASSWD,
        DB,
        PORT,
        null,
        CLIENT_FLAG,
    ) == null) {
        std.debug.print(
            "mysql_real_connect: {s}\n",
            .{mysql_error(db_handle)},
        );
        return error.MySQLConnectionFailed;
    }
    //------------------------------------------------------------
    std.debug.print("connected to {s}:{d}\n", .{ HOST, PORT });
    //------------------------------------------------------------
    {
        if (mysql_query(db_handle, "SELECT VERSION();") != 0) {
            std.debug.print(
                "mysql_query: {s}\n",
                .{mysql_error(db_handle)},
            );
            return error.MySQLQueryError;
        }

        const result = mysql_store_result(db_handle);
        if (result == null) {
            return error.MySQLResultError;
        }
        defer mysql_free_result(result);

        while (mysql_fetch_row(result)) |row| {
            if (row[0]) |version| {
                std.debug.print("version: {s}\n", .{version});
            }
        }
    }
    //------------------------------------------------------------
    {
        const sql =
            \\CREATE DATABASE IF NOT EXISTS test;
            \\USE test;
            \\DROP TABLE IF EXISTS cars;
            \\CREATE TABLE cars(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), price INT DEFAULT 0 NOT NULL, PRIMARY KEY(id));
            \\INSERT INTO cars(name, price) VALUES('Skoda', 9000);
            \\INSERT INTO cars(name, price) VALUES('Audi', 52642);
        ;

        if (mysql_query(db_handle, sql) != 0) {
            std.debug.print("mysql_query: {s}\n", .{mysql_error(db_handle)});
            return error.MySQLQueryError;
        }

        // consume every result generated by each line
        while (true) {
            const result = mysql_store_result(db_handle);

            if (result != null) {
                mysql_free_result(result);
            } else if (mysql_field_count(db_handle) != 0) {
                std.debug.print("mysql_store_result: {s}\n", .{mysql_error(db_handle)});
                return error.MySQLResultError;
            }

            const rc = mysql_next_result(db_handle);

            if (rc == 0) continue;

            if (rc > 0) {
                std.debug.print("mysql_next_result: {s}\n", .{mysql_error(db_handle)});
                return error.MySQLQueryError;
            }

            break;
        }
    }
    //------------------------------------------------------------
    {
        if (mysql_query(db_handle, "SELECT * FROM cars;") != 0) {
            std.debug.print(
                "mysql_query: {s}\n",
                .{mysql_error(db_handle)},
            );
            return error.MySQLQueryError;
        }

        const result = mysql_store_result(db_handle);
        if (result == null) {
            return error.MySQLResultError;
        }
        defer mysql_free_result(result);

        while (mysql_fetch_row(result)) |row| {
            std.debug.print(
                "id: {s}, name: {s}, price: {s}\n",
                .{ row[0].?, row[1].?, row[2].? },
            );
        }
    }
    //------------------------------------------------------------
}
//--------------------------------------------------------------------------------
//################################################################################
//--------------------------------------------------------------------------------
pub const CLIENT_MULTI_STATEMENTS = @as(c_ulong, 1) << @as(c_int, 16);
//--------------------------------------------------------------------------------
pub const MYSQL = anyopaque;
pub const MYSQL_RES = anyopaque;
pub const MYSQL_ROW = [*c][*c]u8;
//--------------------------------------------------------------------------------
pub extern fn mysql_close(sock: ?*MYSQL) callconv(.c) void;
pub extern fn mysql_error(mysql: ?*MYSQL) callconv(.c) [*c]const u8;
pub extern fn mysql_fetch_row(result: ?*MYSQL_RES) callconv(.c) MYSQL_ROW;
pub extern fn mysql_field_count(mysql: ?*MYSQL) callconv(.c) c_uint;
pub extern fn mysql_free_result(result: ?*MYSQL_RES) callconv(.c) void;
pub extern fn mysql_init(mysql: ?*MYSQL) callconv(.c) ?*MYSQL;
pub extern fn mysql_next_result(mysql: ?*MYSQL) callconv(.c) c_int;
pub extern fn mysql_query(mysql: ?*MYSQL, q: [*c]const u8) callconv(.c) c_int;
pub extern fn mysql_real_connect(mysql: ?*MYSQL, host: [*c]const u8, user: [*c]const u8, passwd: [*c]const u8, db: [*c]const u8, port: c_uint, unix_socket: [*c]const u8, clientflag: c_ulong) callconv(.c) ?*MYSQL;
pub extern fn mysql_store_result(mysql: ?*MYSQL) callconv(.c) ?*MYSQL_RES;
//--------------------------------------------------------------------------------
//################################################################################
//--------------------------------------------------------------------------------
