version: "3"

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig016 build-exe ../main.zig -femit-bin=main -lc -lsqlite3 -fstrip -O ReleaseSmall -mcpu=baseline

  debug:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig016 build-exe ../main.zig -femit-bin=main -lc -lsqlite3 -fstrip -O Debug -mcpu=baseline

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmd: ./main

  test:
    dir: "{{.OUTPUT_PATH}}"
    cmd: ./main
