version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig016 build-exe ../math.zig -fstrip -O ReleaseSmall -target wasm32-freestanding -fno-entry --export=add
      - zig016 build-exe ../wasi-args.zig -fstrip -O ReleaseSmall -target wasm32-wasi

  debug:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig016 build-exe ../math.zig -fstrip -O Debug -target wasm32-freestanding -fno-entry --export=add
      - zig016 build-exe ../wasi-args.zig -fstrip -O Debug -target wasm32-wasi

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - silent: true
        cmd: |
          ../call-wasm.ts -- {{.CLI_ARGS}}
          wasmtime wasi-args.wasm 123 hello
